# Generated by Django 5.2.8 on 2025-11-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default=123456789012, editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
