# Generated by Django 5.2.8 on 2025-12-07 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quoted_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_by', to='posts.post'),
        ),
    ]
