# Generated by Django 5.2.8 on 2025-12-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_quoted_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.BooleanField(default=False),
        ),
    ]
