# Generated by Django 5.2.8 on 2025-12-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commented_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
